# Generated by Django 6.0 on 2026-01-16 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_add_firefly_importer_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJobQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_id', models.IntegerField()),
                ('extraction_id', models.IntegerField(blank=True, null=True)),
                ('external_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='PENDING')),
                ('priority', models.IntegerField(default=0, help_text='Higher = processed first')),
                ('scheduled_at', models.TextField(help_text='When the job was added to queue')),
                ('scheduled_for', models.TextField(blank=True, help_text='When to process (NULL = ASAP based on interval)', null=True)),
                ('started_at', models.TextField(blank=True, null=True)),
                ('completed_at', models.TextField(blank=True, null=True)),
                ('suggestions_json', models.TextField(blank=True, help_text='JSON with AI suggestions for each field', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_by', models.TextField(blank=True, help_text='AUTO, USER, or SYSTEM', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Job',
                'verbose_name_plural': 'AI Job Queue',
                'db_table': 'ai_job_queue',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyncPoolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('category', 'Category'), ('tag', 'Tag'), ('account', 'Account'), ('piggy_bank', 'Piggy Bank')], max_length=50)),
                ('firefly_id', models.IntegerField(help_text="ID in owner's Firefly instance")),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA256 hash for deduplication across instances', max_length=64)),
                ('data_json', models.TextField(help_text='Full entity data for display/import')),
                ('name', models.CharField(help_text='Denormalized for display', max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_pool_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Pool Record',
                'verbose_name_plural': 'Sync Pool Records',
            },
        ),
        migrations.CreateModel(
            name='SyncImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('fingerprint', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('skipped', 'Skipped (already exists)'), ('error', 'Error')], max_length=20)),
                ('target_firefly_id', models.IntegerField(blank=True, help_text="ID in importer's Firefly if created", null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('source_owner', models.ForeignKey(blank=True, help_text='Original owner of the pool record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_imports', to=settings.AUTH_USER_MODEL)),
                ('pool_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.syncpoolrecord')),
            ],
            options={
                'verbose_name': 'Sync Import Log',
                'verbose_name_plural': 'Sync Import Logs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncPoolShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='web.syncpoolrecord')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_sync_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_sync_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Pool Share',
                'verbose_name_plural': 'Sync Pool Shares',
            },
        ),
        migrations.AddIndex(
            model_name='syncpoolrecord',
            index=models.Index(fields=['entity_type', 'fingerprint'], name='web_syncpoo_entity__dc1494_idx'),
        ),
        migrations.AddIndex(
            model_name='syncpoolrecord',
            index=models.Index(fields=['owner', 'entity_type'], name='web_syncpoo_owner_i_fe2f31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncpoolrecord',
            unique_together={('owner', 'entity_type', 'fingerprint')},
        ),
        migrations.AlterUniqueTogether(
            name='syncpoolshare',
            unique_together={('record', 'shared_with')},
        ),
    ]
