# Generated by Django 5.2.9 on 2026-01-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_aijobqueue_syncpoolrecord_syncimportlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncpoolrecord',
            name='entity_type',
            field=models.CharField(choices=[('category', 'Category'), ('tag', 'Tag'), ('budget', 'Budget'), ('rule_group', 'Rule Group'), ('currency', 'Currency'), ('account', 'Account'), ('bill', 'Bill'), ('piggy_bank', 'Piggy Bank'), ('rule', 'Rule'), ('recurrence', 'Recurrence'), ('transaction', 'Transaction')], max_length=50),
        ),
    ]
